name: Publish to Github

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.1
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile --no-progress
      - run: yarn test
      - run: yarn tsc

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.1
          registry-url: https://npm.pkg.github.com/
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile --no-progress
      - run: |
          NEW_VERSION=$(echo ${{ github.event.GITHUB_REF }} | sed -e 's/^v//')
          yarn version $NEW_VERSION --new-version --no-git-tag-version
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
